# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/group5-2/.local/lib/python3.9/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/group5-2/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/group5-2/NatTrial/RTES_Table_Tennis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/group5-2/NatTrial/RTES_Table_Tennis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/group5-2/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/group5-2/.local/lib/python3.9/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/group5-2/NatTrial/RTES_Table_Tennis/CMakeFiles /home/group5-2/NatTrial/RTES_Table_Tennis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/group5-2/NatTrial/RTES_Table_Tennis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named icm20948

# Build rule for target.
icm20948: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icm20948
.PHONY : icm20948

# fast build rule for target.
icm20948/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icm20948.dir/build.make CMakeFiles/icm20948.dir/build
.PHONY : icm20948/fast

#=============================================================================
# Target rules for targets named imu_publisher

# Build rule for target.
imu_publisher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imu_publisher
.PHONY : imu_publisher

# fast build rule for target.
imu_publisher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imu_publisher.dir/build.make CMakeFiles/imu_publisher.dir/build
.PHONY : imu_publisher/fast

#=============================================================================
# Target rules for targets named pi3sender

# Build rule for target.
pi3sender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pi3sender
.PHONY : pi3sender

# fast build rule for target.
pi3sender/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi3sender.dir/build.make CMakeFiles/pi3sender.dir/build
.PHONY : pi3sender/fast

IMU_processing/IMUPublisher/IMUPublisher.o: IMU_processing/IMUPublisher/IMUPublisher.cpp.o
.PHONY : IMU_processing/IMUPublisher/IMUPublisher.o

# target to build an object file
IMU_processing/IMUPublisher/IMUPublisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imu_publisher.dir/build.make CMakeFiles/imu_publisher.dir/IMU_processing/IMUPublisher/IMUPublisher.cpp.o
.PHONY : IMU_processing/IMUPublisher/IMUPublisher.cpp.o

IMU_processing/IMUPublisher/IMUPublisher.i: IMU_processing/IMUPublisher/IMUPublisher.cpp.i
.PHONY : IMU_processing/IMUPublisher/IMUPublisher.i

# target to preprocess a source file
IMU_processing/IMUPublisher/IMUPublisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imu_publisher.dir/build.make CMakeFiles/imu_publisher.dir/IMU_processing/IMUPublisher/IMUPublisher.cpp.i
.PHONY : IMU_processing/IMUPublisher/IMUPublisher.cpp.i

IMU_processing/IMUPublisher/IMUPublisher.s: IMU_processing/IMUPublisher/IMUPublisher.cpp.s
.PHONY : IMU_processing/IMUPublisher/IMUPublisher.s

# target to generate assembly for a file
IMU_processing/IMUPublisher/IMUPublisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imu_publisher.dir/build.make CMakeFiles/imu_publisher.dir/IMU_processing/IMUPublisher/IMUPublisher.cpp.s
.PHONY : IMU_processing/IMUPublisher/IMUPublisher.cpp.s

IMU_processing/imu_settings/icm20948_utils.o: IMU_processing/imu_settings/icm20948_utils.cpp.o
.PHONY : IMU_processing/imu_settings/icm20948_utils.o

# target to build an object file
IMU_processing/imu_settings/icm20948_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icm20948.dir/build.make CMakeFiles/icm20948.dir/IMU_processing/imu_settings/icm20948_utils.cpp.o
.PHONY : IMU_processing/imu_settings/icm20948_utils.cpp.o

IMU_processing/imu_settings/icm20948_utils.i: IMU_processing/imu_settings/icm20948_utils.cpp.i
.PHONY : IMU_processing/imu_settings/icm20948_utils.i

# target to preprocess a source file
IMU_processing/imu_settings/icm20948_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icm20948.dir/build.make CMakeFiles/icm20948.dir/IMU_processing/imu_settings/icm20948_utils.cpp.i
.PHONY : IMU_processing/imu_settings/icm20948_utils.cpp.i

IMU_processing/imu_settings/icm20948_utils.s: IMU_processing/imu_settings/icm20948_utils.cpp.s
.PHONY : IMU_processing/imu_settings/icm20948_utils.s

# target to generate assembly for a file
IMU_processing/imu_settings/icm20948_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icm20948.dir/build.make CMakeFiles/icm20948.dir/IMU_processing/imu_settings/icm20948_utils.cpp.s
.PHONY : IMU_processing/imu_settings/icm20948_utils.cpp.s

IMU_processing/imudriver/icm20948_i2c.o: IMU_processing/imudriver/icm20948_i2c.cpp.o
.PHONY : IMU_processing/imudriver/icm20948_i2c.o

# target to build an object file
IMU_processing/imudriver/icm20948_i2c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icm20948.dir/build.make CMakeFiles/icm20948.dir/IMU_processing/imudriver/icm20948_i2c.cpp.o
.PHONY : IMU_processing/imudriver/icm20948_i2c.cpp.o

IMU_processing/imudriver/icm20948_i2c.i: IMU_processing/imudriver/icm20948_i2c.cpp.i
.PHONY : IMU_processing/imudriver/icm20948_i2c.i

# target to preprocess a source file
IMU_processing/imudriver/icm20948_i2c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icm20948.dir/build.make CMakeFiles/icm20948.dir/IMU_processing/imudriver/icm20948_i2c.cpp.i
.PHONY : IMU_processing/imudriver/icm20948_i2c.cpp.i

IMU_processing/imudriver/icm20948_i2c.s: IMU_processing/imudriver/icm20948_i2c.cpp.s
.PHONY : IMU_processing/imudriver/icm20948_i2c.s

# target to generate assembly for a file
IMU_processing/imudriver/icm20948_i2c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icm20948.dir/build.make CMakeFiles/icm20948.dir/IMU_processing/imudriver/icm20948_i2c.cpp.s
.PHONY : IMU_processing/imudriver/icm20948_i2c.cpp.s

pi3_sender.o: pi3_sender.cpp.o
.PHONY : pi3_sender.o

# target to build an object file
pi3_sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi3sender.dir/build.make CMakeFiles/pi3sender.dir/pi3_sender.cpp.o
.PHONY : pi3_sender.cpp.o

pi3_sender.i: pi3_sender.cpp.i
.PHONY : pi3_sender.i

# target to preprocess a source file
pi3_sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi3sender.dir/build.make CMakeFiles/pi3sender.dir/pi3_sender.cpp.i
.PHONY : pi3_sender.cpp.i

pi3_sender.s: pi3_sender.cpp.s
.PHONY : pi3_sender.s

# target to generate assembly for a file
pi3_sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi3sender.dir/build.make CMakeFiles/pi3sender.dir/pi3_sender.cpp.s
.PHONY : pi3_sender.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... icm20948"
	@echo "... imu_publisher"
	@echo "... pi3sender"
	@echo "... IMU_processing/IMUPublisher/IMUPublisher.o"
	@echo "... IMU_processing/IMUPublisher/IMUPublisher.i"
	@echo "... IMU_processing/IMUPublisher/IMUPublisher.s"
	@echo "... IMU_processing/imu_settings/icm20948_utils.o"
	@echo "... IMU_processing/imu_settings/icm20948_utils.i"
	@echo "... IMU_processing/imu_settings/icm20948_utils.s"
	@echo "... IMU_processing/imudriver/icm20948_i2c.o"
	@echo "... IMU_processing/imudriver/icm20948_i2c.i"
	@echo "... IMU_processing/imudriver/icm20948_i2c.s"
	@echo "... pi3_sender.o"
	@echo "... pi3_sender.i"
	@echo "... pi3_sender.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

